### PR TITLE
Fix install instructions related to Apple M1

### LINKED ISSUE #17: README instructions for conda are wrong.
1. include a link to install conda (don't assume people know of or have it).

```
conda env create -f scitt-api-emulator.yml
conda activate scitt
```

This yields the following error on macOS:
```
EnvironmentFileNotFound: '/Users/USER/.../scitt-api-emulator/scitt-api-emulator.yml' file not found
(base) 
```

### PR DESCRIPTION
**Pull request by OR13**
Attempting to resolve: https://github.com/scitt-community/scitt-api-emulator/issues/17

I still get errors even after the corrections made in the branch... I think in may be Apple M1 related...

See this trace:

```
Package colorama conflicts for:
flask=2.2.2 -> click[version='>=8.0'] -> colorama
pytest=7.2.1 -> coloramaThe following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__unix==0=0
  - feature:|@/osx-arm64::__unix==0=0
  - flask=2.2.2 -> click[version='>=8.0'] -> __unix
  - flask=2.2.2 -> click[version='>=8.0'] -> __win

Your installed version is: 0
```

This command fails, due to environment setup failure on Apple M1.

```
conda activate scitt
```

### CODE REVIEW

File: scitt-emulator.sh [hunk 1]
```diff
@@ -6,7 +6,7 @@ set -e
 
 if [ ! -f "venv/bin/activate" ]; then
     echo "Setting up Python virtual environment."
-    python3.8 -m venv "venv"
```
Comment (OR13) [inline scitt-emulator.sh:9]: This worked for me on Apple M1 default python version is higher, don't think we need the pin here.

File: environment.yml [hunk 2]
```diff
@@ -20,6 +20,7 @@ dependencies:
   - rfc3986=1.5.0
   - setuptools=66.1.1
   - wheel=0.38.4
+  - pip=22.3.1
```
Comment (OR13) [inline environment.yml:23]: fixes a warning from conda

File: README.md [hunk 3]
```diff
@@ -11,10 +11,15 @@ On Ubuntu, run the following to install Python:
...
+
+If you want to use conda, first install it:
+
+- [Install Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html)
+
+You can get things setup with the following:
 
 ```sh
-conda env create -f scitt-api-emulator.yml
+conda env create -f environment.yml
```
Comment (OR13) [inline README.md:22]: file name in repo was not correct.

File: README.md [hunk 4]
```diff
@@ -11,10 +11,15 @@ On Ubuntu, run the following to install Python:
 sudo apt install python3.8 python3.8-venv
 ```
 
-or, if you are running a conda environment, you can get things setup with the following:
+
+If you want to use conda, first install it:
+
+- [Install Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html)
```
Comment (OR13) [inline README.md:17]: instructions for installing conda on linux, windows for macOS

File: scitt-emulator.sh (hunk 1 above)
Comment (letmaik) [reply scitt-emulator.sh:9]: On Linux, `python` will still mostly give you Python 2 unfortunately. Does `python3` work on Apple?

Comment (OR13) [reply scitt-emulator.sh:9]: It did for me, after removing the pinning.

Comment (letmaik) [reply scitt-emulator.sh:9]: We should have something that works both on Linux and macOS I think.

Comment (OR13) [reply scitt-emulator.sh:9]: Are those really the only 2 operating systems that matter? ; )

Comment (OR13) [reply scitt-emulator.sh:9]: Maybe there is a better way to fix the script, I am not really a "python" expert.

In node.js we use `nvm` and `npm` scripts for this kind of thing.

Comment (letmaik) [reply scitt-emulator.sh:9]: Does `python3` work for you? For Windows, we can rely on WSL..

File: scitt-emulator.sh [hunk 5]
```diff
@@ -6,7 +6,7 @@ set -e
...
+    python -m venv "venv"
```
Comment (OR13) [inline scitt-emulator.sh]:
```suggestion
    python3 -m venv "venv"
```

File: scitt-emulator.sh (hunk 1 above)
Comment (OR13) [reply scitt-emulator.sh:9]: yes, `python3` works, I updated the PR to use it.

**Review by letmaik — APPROVED** [review]
